### ISSUE TITLE
Cannot read properties of undefined (reading 'current') error

### ISSUE THREAD

**Issue by gut4** [drcmda/react-zdog#33] opened 2023-08-07 23:01 UTC
I try to use react-zdog@1.2.0 with [remix.run](https://github.com/remix-run/remix) and with create-react-app.
In both cases i get error
```
Cannot read properties of undefined (reading 'current')
```
I also try react-zdog@1.1.1 
Basic example works fine:
```
<Illustration zoom={8}>
    <Shape stroke={20} color="lightblue" rotate={{ x: Math.PI }} />
  </Illustration>
```
But when i try ```const {illu, scene, size} = useZdog()``` I get the same error:
```
TypeError: Cannot read properties of undefined (reading 'current')
    at useZdog (http://localhost:3000/build/routes/zdog-XXTCYKP4.js:2376:16)
    at Zdog2 (http://localhost:3000/build/routes/zdog-XXTCYKP4.js:2523:7)
    at renderWithHooks (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:12171:26)
    at mountIndeterminateComponent (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:14921:21)
    at beginWork (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:15902:22)
    at beginWork$1 (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:19749:22)
    at performUnitOfWork (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:19194:20)
    at workLoopSync (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:19133:13)
    at renderRootSync (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:19112:15)
    at recoverFromConcurrentError (http://localhost:3000/build/_shared/chunk-GIAAE3CH.js:18732:28)
```
zdog-XXTCYKP4.js:2376:16
```
function useZdog() {
  const state = (0, import_react.useContext)(stateContext);
  return state.current;
}
```

**Comment by bhushan6** [comment] 2023-08-07 23:32
Just published a fix. Please try with version 1.2.1 now. [working example](https://stackblitz.com/edit/stackblitz-starters-bquhc7?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js,src%2Fstyle.css&title=React%20Starter) . Please try and let me know.

**Comment by gut4** [comment] 2023-08-08 01:03
When I add ```const {illu, scene, size} = useZdog()``` I still getting error 
```
Error in /turbo_modules/react-zdog@1.2.1/dist/index.cjs.js (131:16)
Cannot read properties of undefined (reading 'current')
```

**Comment by bhushan6** [comment] 2023-08-08 05:32
are you using it inside `Illustartion` component? can you reproduce the issue [here](https://stackblitz.com/edit/stackblitz-starters-bquhc7?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js,src%2Fstyle.css&title=React%20Starter)

**Comment by gut4** [comment] 2023-08-08 05:46
just this code already throws an error

```
import React from 'react';
import './style.css';

import { Illustration, Ellipse, useZdog } from 'react-zdog';

const TAU = Math.PI * 2;

export default function App() {
  const { illu, scene, size } = useZdog();

  return (
    <Illustration zoom={8}>
      <Ellipse
        diameter={20}
        rotate={{ x: -TAU / 3 }}
        translate={{ y: 15, z: -100 }}
        stroke={4}
        color="#ff0000"
        fill
      />
    </Illustration>
  );
}
```
```
Error in /turbo_modules/react-zdog@1.2.1/dist/index.cjs.js (131:16)
Cannot read properties of undefined (reading 'current')
```

**Comment by bhushan6** [comment] 2023-08-08 07:31
Yeah, thats the wrong way. You can't use `useZdog` outside of  `Illustration` because `Illustration` is context provider for that hook and state object is value of that context so when you use it outside of that component it is null and thats why it throws an error when you try to destructure it. [This](https://stackblitz.com/edit/stackblitz-starters-bquhc7?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js,src%2Fstyle.css&title=React%20Starter) is the way to use it.

**Comment by bhushan6** [comment] 2023-08-08 08:28
I think it solves the issue, so closing it here.

**Closed as completed by bhushan6** 2023-08-08 08:28 UTC
